### ISSUE TITLE
Manim issue

### ISSUE THREAD

**Issue by Morwan2** [Rickaym/manim-sideview#108]
When i do the manim side view thingy its says

Manim Extension XTerm
Serves as a terminal for logging purpose.

Extension Version 0.2.16

MSV c:\Users\LENOVO\Desktop\Code>"c:\Users\LENOVO\miniforge3\envs\my-manim-environment\Scripts\manim" "c:\Users\LENOVO\Desktop\Code\main.py" FibonacciSequence
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\Users\LENOVO\miniforge3\envs\my-manim-environment\Scripts\manim.exe\__main__.py", line 4, in <module>
    from manim.__main__ import main
  File "C:\Users\LENOVO\miniforge3\envs\my-manim-environment\Lib\site-packages\manim\__init__.py", line 13, in <module>
    from ._config import *
  File "C:\Users\LENOVO\miniforge3\envs\my-manim-environment\Lib\site-packages\manim\_config\__init__.py", line 7, in <module>
    from .logger_utils import make_logger
  File "C:\Users\LENOVO\miniforge3\envs\my-manim-environment\Lib\site-packages\manim\_config\logger_utils.py", line 21, in <module>
    from rich import color, errors
ModuleNotFoundError: No module named 'rich'
[24304] Execution returned code=1 in 0.912 seconds returned signal null 

please help

**Comment by uwezi** [comment]
I would say that this is a clear error message, you are missing the `rich` Python library, which is imported as 
```from rich import color, errors```

Normally such dependencies should be automatically installed when you install Manim, but since I don't know more about your system or how you installed Manim I can not even guess what went wrong.

You seem to be using a miniconda environment - apart from having heard about it, I don't know how its managed, but you should somehow be able to add the missing dependency using `pip install rich`

https://pypi.org/project/rich/

**Comment by Morwan2** [comment]
I installed manim using conda because i cant use choco or scoop

**Comment by Morwan2** [comment]
Its mostly about the side manim view thingy when I do it from the terminal to export it its fine

**Comment by Rickaym** [comment]
> Its mostly about the side manim view extension for vs code thingy when I do it from the terminal to export it its fine

I suspect you're running different environments. Make sure that all the required packages are installed in `my-manim-environment`.
